import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * A single autogenerated sidebar — items are ordered by the `sidebar_position`
 * front matter in each doc under `docs/`.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
